"""Add is_completed to goals

Revision ID: 2add7e06a7a7
Revises: 687a3d1e5092
Create Date: 2025-08-28 14:15:03.151236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2add7e06a7a7'
down_revision = '687a3d1e5092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
